### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by HIN0209** [plabadille/image_classifier#1]
@plabadille 
Great work! I enjoyed your codes (Ubuntu 14.04, python 3.5, GeForce 1080Ti). Although it eventually worked, let me point out some typos/discrepancy with readme.

In: Test your freshly computed model
1: Paste your test pictures into image_classifier/data_dir_test/* and run; 
there is no preexisting data_dir_test in my environment, rather there is data_to_predict.
2: python predict.py save/image_classifier_datetime_n 
This did not work, rather, save/image_classifier_datetime/image_classifier_datetime_n worked, because there was a folder entitled image_classifier_datetime.

**Comment by plabadille** [comment]
Thanks for your feedback @HIN0209 
I'm happy you liked it. I just corrected the two typo issue : 
1) It's a typo error, the test data_dir is data_to_predict as well.
2) That's correct too, this is a README error.

Since you enjoy the code, I just push a temporary branch (https://github.com/plabadille/image_classifier/tree/v1.1_wip) where some important things are fixed (about model pertinence): 
- The cross validation (StratifiedKFold) I use does'nt work as expected so I removed it. It's maybe the reason why nobody is using it...
- I also remove data augmentation for now because it's messing around with my custom iterator (_NEXT conflict). I have to upgrade the generator to Sequences but haven't got the time yet.
